// Generated by Laravel Forgemate Initializer
export const PERMISSION_VALID_ACTIONS = [
    'create',
    'import',
    'read',
    'read-all',
    'read-partial',
    'download',
    'update',
    'delete',
    'export',
];
