// Generated by Laravel Forgemate Initializer
export const ROUTES = {
    DASHBOARD: 'dashboard',
    LOGIN: 'login',
    REGISTER: 'register',
    FORGOT_PASSWORD: 'forgot-password',
    RESET_PASSWORD: 'reset-password',
    PASSWORD_REQUEST: 'password.request',
    PROFILE: 'profile',
    USERS: 'users',
    ROLES: 'roles',
    PERMISSIONS: 'permissions',
    
    // Add your application routes here
};
