// Generated by Laravel Forgemate Initializer
export const STYLING = {
    ICON: {
        SIZE: {
            EXTRA_SMALL: 14,
            SMALL: 20,
            MEDIUM: 40,
            LARGE: 60,
        },
        COLOR: {
            PRIMARY: 'primary',
            SECONDARY: 'secondary',
            DEFAULT: 'default',
        },
    },
};
